### ISSUE TITLE
Sessions should be clean for new Browser objects

### ISSUE THREAD

**Issue by ozroc** [hickford/MechanicalSoup#74] opened 2017-07-11 12:32 UTC
Let's say I start a browser:

`b1 = mechanicalsoup.Browser(soup_config={'features': 'html'})`

Do several things and start later a second one:

`b2 = mechanicalsoup.Browser(soup_config={'features': 'html'})`

The session for the second browser is taken from: 

`requests.Session()`

And cookies there (in requests library) are stored as a mutable object in Session class. This causes the second browser to start with the cookies (and all other session attributes) from the first one, which is an unexpected and quite weird behavior.

In my use case, I simply had to clear cookies just after creating the second browser instance:

`b2.session.cookies.clear()`

I think it should be easy to assure a clean session is used for each new browser instance (a natural way could be using context managers).

**Comment by boarnasia** [comment] 2017-08-11 00:58
In my environment, new Session comes with new cookies.

```python
>>> import requests
>>> s1 = requests.Session()
>>> s1.get('http://httpbin.org/cookies/set/sessioncookie/123456789')
<Response [200]>
>>> s1.cookies.keys()
['sessioncookie']
>>> s2 = requests.Session()
>>> s2.cookies.keys()
[]
>>>
```

This behaviour is also the same as that of mechanicalsoup.

```python
>>> from mechanicalsoup import Browser
>>> b1 = Browser(soup_config={'features': 'html'})
>>> ret = b1.get('http://httpbin.org/cookies/set/sessioncookie/123456789')
>>> b1.session.cookies.keys()
['sessioncookie']
>>> b2 = Browser(soup_config={'features': 'html'})
>>> b2.session.cookies.keys()
[]
```
I think there's no issues.

**Comment by boarnasia** [comment] 2017-08-11 04:37
However, it's not good that browser finishes without closing own session when  being destroyed.

I think it needs close() and \_\_del\_\_ methods like this:

```python
class Browser(object):
    ...

    def close(self):
        """Close the current session"""
        self.session.cookies.clear()
        self.session.close()

    def __del__(self):
        self.close()
```

**Comment by moy** [comment] 2017-08-12 07:51
Indeed, @ozroc, I can't reproduce. `requests.Session()` is not a shared variable, but a call to the constructor of `Session`, it creates a different object each time. I'll close the issue, but please reopen with a more specific test-case (a real program as much as possible) if you think the issue is actually there.

@boarnasia: good suggestion, I've just added these `close` and `__del__` methods. Thanks.

**Closed by moy** 2017-08-12 07:51 UTC
